dependencies:
  - python=3.12
  - pip
  - pip:
    - ..  # mlc-en repo
    - --pre
    - mlc-ai-nightly-cpu
    - -f https://mlc.ai/wheels
    - sphinx==5.3.0
    - sphinxcontrib-bibtex<2.6
    - pybtex<0.25
